services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true

      - traefik.http.routers.wikigraph-http.rule=Host(`wikigraph.eryk.one`)
      - traefik.http.routers.wikigraph-http.entrypoints=web
      - traefik.http.routers.wikigraph-http.middlewares=wikigraph-https-redirect
      - traefik.http.routers.wikigraph-http.service=wikigraph

      - traefik.http.middlewares.wikigraph-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.wikigraph-https-redirect.redirectscheme.permanent=true

      - traefik.http.routers.wikigraph.rule=Host(`wikigraph.eryk.one`)
      - traefik.http.routers.wikigraph.entrypoints=websecure
      - traefik.http.routers.wikigraph.tls=true
      - traefik.http.routers.wikigraph.tls.certresolver=letsencrypt
      - traefik.http.services.wikigraph.loadbalancer.server.port=80
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
