[tools]
caddy = "latest"
node = "latest"

[tasks.docker]
run = """
docker build -t wikigraph:latest .
docker run --rm -it \
  --name wikigraph-app \
  -p 3000:80 \
  wikigraph:latest
"""

[tasks.check]
run = """
npm run lint
npm run build
"""

[tasks.format]
run = """
npm run format
caddy fmt --overwrite
"""

